---
# handlers file for netiq-sentinel-syslog-event-source
- name: restart syslog
  become: true
  service: name=syslog state=restarted

- name: restart rsyslog
  become: true
  service: name=rsyslog state=restarted

- name: send magic message
  command: logger -t kernel {{ sentinel_collector_magic }}
