---
# handlers file for netiq-sentinel-syslog-event-source
- name: restart rsyslog
  become: true
  service: name={{ syslog_service_name }} state=restarted

- name: send magic message
  command: /usr/bin/logger -t kernel {{ sentinel_collector_magic }}
