---
# handlers file for netiq-sentinel-syslog-event-source
- name: restart syslog
  become: true
  service: name={{ syslog_service_name }} state=restarted

- name: send magic message
  shell: logger -t kernel {{ sentinel_collector_magic }}
